views:
  - title: Test environment
    cards:
      - type: 'custom:gcclock-simple'
        entity: switch.decorative_lights
        title_template: Switch
        hours_to_show: 1
      - type: 'button'
        entity: switch.decorative_lights
      - type: 'tile'
        entity: sun.sun
